export type Department = {
  code: string
  nom: string
  slug: string
  region: string
  prefecture: string
  villesPrincipales: string[]
  climat: string
  toitureDominante: string
  description: string
}

export const PARTNER_SITES = {
  traitementBois: {
    url: "https://traitement-bois.fr",
    label: "Diagnostic Traitement Bois",
    description: "Detectez les infestations de termites, capricornes et champignons lignivores. Traitement preventif et curatif de votre charpente.",
  },
  humidite: {
    url: "https://humidite.aco-habitat.fr",
    label: "Diagnostic Humidite",
    description: "Identifiez les problemes d'humidite : remontees capillaires, infiltrations, condensation. Solutions adaptees a votre habitat.",
  },
}

export const departments: Department[] = [
  { code: "01", nom: "Ain", slug: "couvreur-toiture-ain-01", region: "Auvergne-Rhone-Alpes", prefecture: "Bourg-en-Bresse", villesPrincipales: ["Bourg-en-Bresse", "Oyonnax", "Amberieu-en-Bugey", "Bellegarde-sur-Valserine", "Miribel"], climat: "semi-continental", toitureDominante: "tuile mecanique et tuile plate", description: "Dans l'Ain, entre plaines de la Dombes et montagnes du Jura, les toitures subissent des ecarts de temperature importants et des precipitations regulieres." },
  { code: "02", nom: "Aisne", slug: "couvreur-toiture-aisne-02", region: "Hauts-de-France", prefecture: "Laon", villesPrincipales: ["Saint-Quentin", "Laon", "Soissons", "Chateau-Thierry", "Tergnier"], climat: "oceanique degrade", toitureDominante: "ardoise et tuile plate du nord", description: "Dans l'Aisne, le climat humide des Hauts-de-France favorise le developpement de mousse et lichen sur les toitures en ardoise." },
  { code: "03", nom: "Allier", slug: "couvreur-toiture-allier-03", region: "Auvergne-Rhone-Alpes", prefecture: "Moulins", villesPrincipales: ["Montlucon", "Vichy", "Moulins", "Cusset", "Yzeure"], climat: "semi-continental", toitureDominante: "tuile canal et tuile mecanique", description: "Dans l'Allier, au coeur du Bourbonnais, les hivers rigoureux et les etes chauds mettent a rude epreuve les toitures traditionnelles en tuile." },
  { code: "04", nom: "Alpes-de-Haute-Provence", slug: "couvreur-toiture-alpes-haute-provence-04", region: "Provence-Alpes-Cote d'Azur", prefecture: "Digne-les-Bains", villesPrincipales: ["Manosque", "Digne-les-Bains", "Sisteron", "Forcalquier", "Chateau-Arnoux-Saint-Auban"], climat: "mediterraneen montagnard", toitureDominante: "tuile canal provencale et lauze", description: "Dans les Alpes-de-Haute-Provence, l'altitude et le mistral imposent des contraintes specifiques aux toitures en tuile canal et lauze." },
  { code: "05", nom: "Hautes-Alpes", slug: "couvreur-toiture-hautes-alpes-05", region: "Provence-Alpes-Cote d'Azur", prefecture: "Gap", villesPrincipales: ["Gap", "Briancon", "Embrun", "Laragne-Monteglin", "Veynes"], climat: "montagnard", toitureDominante: "lauze et bac acier", description: "Dans les Hautes-Alpes, les fortes chutes de neige et le gel demandent des toitures extremement resistantes." },
  { code: "06", nom: "Alpes-Maritimes", slug: "couvreur-toiture-alpes-maritimes-06", region: "Provence-Alpes-Cote d'Azur", prefecture: "Nice", villesPrincipales: ["Nice", "Antibes", "Cannes", "Grasse", "Cagnes-sur-Mer"], climat: "mediterraneen", toitureDominante: "tuile canal et tuile romane", description: "Dans les Alpes-Maritimes, le soleil intense et les orages violents d'automne necessitent un entretien regulier des toitures en tuile." },
  { code: "07", nom: "Ardeche", slug: "couvreur-toiture-ardeche-07", region: "Auvergne-Rhone-Alpes", prefecture: "Privas", villesPrincipales: ["Annonay", "Aubenas", "Privas", "Tournon-sur-Rhone", "Le Teil"], climat: "mediterraneen a semi-continental", toitureDominante: "tuile canal et lauze", description: "En Ardeche, la diversite des reliefs entre vallees et plateaux impose des toitures variees, soumises aux vents et episodes cevenols." },
  { code: "08", nom: "Ardennes", slug: "couvreur-toiture-ardennes-08", region: "Grand Est", prefecture: "Charleville-Mezieres", villesPrincipales: ["Charleville-Mezieres", "Sedan", "Rethel", "Revin", "Fumay"], climat: "continental", toitureDominante: "ardoise et zinc", description: "Dans les Ardennes, les hivers rudes et les fortes precipitations fragilisent les toitures en ardoise traditionnelles de la region." },
  { code: "09", nom: "Ariege", slug: "couvreur-toiture-ariege-09", region: "Occitanie", prefecture: "Foix", villesPrincipales: ["Pamiers", "Foix", "Saint-Girons", "Lavelanet", "Saverdun"], climat: "montagnard a oceanique", toitureDominante: "ardoise pyreneenne et tuile canal", description: "En Ariege, au pied des Pyrenees, les toitures en ardoise locale doivent resister a la neige abondante et aux vents de montagne." },
  { code: "10", nom: "Aube", slug: "couvreur-toiture-aube-10", region: "Grand Est", prefecture: "Troyes", villesPrincipales: ["Troyes", "Romilly-sur-Seine", "La Chapelle-Saint-Luc", "Sainte-Savine", "Bar-sur-Aube"], climat: "oceanique degrade", toitureDominante: "tuile plate de Bourgogne et ardoise", description: "Dans l'Aube, les toitures traditionnelles en tuile plate champenoise sont soumises aux pluies frequentes et aux gelees hivernales." },
  { code: "11", nom: "Aude", slug: "couvreur-toiture-aude-11", region: "Occitanie", prefecture: "Carcassonne", villesPrincipales: ["Narbonne", "Carcassonne", "Castelnaudary", "Lezignan-Corbieres", "Limoux"], climat: "mediterraneen", toitureDominante: "tuile canal meridionale", description: "Dans l'Aude, le vent d'autan et la tramontane soumettent les toitures en tuile canal a des contraintes mecaniques importantes." },
  { code: "12", nom: "Aveyron", slug: "couvreur-toiture-aveyron-12", region: "Occitanie", prefecture: "Rodez", villesPrincipales: ["Rodez", "Millau", "Villefranche-de-Rouergue", "Onet-le-Chateau", "Decazeville"], climat: "semi-continental a montagnard", toitureDominante: "lauze et ardoise", description: "En Aveyron, les toitures en lauze traditionnelles subissent des hivers rigoureux sur les causses et plateaux du Rouergue." },
  { code: "13", nom: "Bouches-du-Rhone", slug: "couvreur-toiture-bouches-du-rhone-13", region: "Provence-Alpes-Cote d'Azur", prefecture: "Marseille", villesPrincipales: ["Marseille", "Aix-en-Provence", "Arles", "Martigues", "Salon-de-Provence"], climat: "mediterraneen", toitureDominante: "tuile canal et tuile romane", description: "Dans les Bouches-du-Rhone, le mistral violent et le soleil intense degradent les toitures en tuile canal provencale." },
  { code: "14", nom: "Calvados", slug: "couvreur-toiture-calvados-14", region: "Normandie", prefecture: "Caen", villesPrincipales: ["Caen", "Lisieux", "Herouville-Saint-Clair", "Bayeux", "Vire-Normandie"], climat: "oceanique", toitureDominante: "ardoise et tuile plate normande", description: "Dans le Calvados, le climat oceanique humide favorise la pousse de mousse et lichen sur les toitures en ardoise normande." },
  { code: "15", nom: "Cantal", slug: "couvreur-toiture-cantal-15", region: "Auvergne-Rhone-Alpes", prefecture: "Aurillac", villesPrincipales: ["Aurillac", "Saint-Flour", "Mauriac", "Arpajon-sur-Cere", "Ytrac"], climat: "montagnard", toitureDominante: "lauze et ardoise", description: "Dans le Cantal, les toitures en lauze volcanique traditionnelles doivent supporter la neige abondante et les vents d'altitude." },
  { code: "16", nom: "Charente", slug: "couvreur-toiture-charente-16", region: "Nouvelle-Aquitaine", prefecture: "Angouleme", villesPrincipales: ["Angouleme", "Cognac", "Soyaux", "La Couronne", "Ruelle-sur-Touvre"], climat: "oceanique", toitureDominante: "tuile canal et tuile romane", description: "En Charente, le climat doux et humide entraine un vieillissement premature des toitures en tuile canal par colonisation vegetale." },
  { code: "17", nom: "Charente-Maritime", slug: "couvreur-toiture-charente-maritime-17", region: "Nouvelle-Aquitaine", prefecture: "La Rochelle", villesPrincipales: ["La Rochelle", "Saintes", "Rochefort", "Royan", "Tonnay-Charente"], climat: "oceanique littoral", toitureDominante: "tuile canal et tuile romane", description: "En Charente-Maritime, l'air salin du littoral et les tempetes atlantiques accelerent la corrosion des toitures." },
  { code: "18", nom: "Cher", slug: "couvreur-toiture-cher-18", region: "Centre-Val de Loire", prefecture: "Bourges", villesPrincipales: ["Bourges", "Vierzon", "Saint-Amand-Montrond", "Mehun-sur-Yevre", "Saint-Doulchard"], climat: "oceanique degrade", toitureDominante: "tuile plate et ardoise", description: "Dans le Cher, au coeur du Berry, les toitures traditionnelles en tuile plate subissent les gelees hivernales et l'humidite." },
  { code: "19", nom: "Correze", slug: "couvreur-toiture-correze-19", region: "Nouvelle-Aquitaine", prefecture: "Tulle", villesPrincipales: ["Brive-la-Gaillarde", "Tulle", "Ussel", "Malemort", "Egletons"], climat: "oceanique a semi-continental", toitureDominante: "ardoise et lauze", description: "En Correze, les fortes precipitations du Limousin et les hivers froids mettent a l'epreuve les toitures en ardoise locale." },
  { code: "2A", nom: "Corse-du-Sud", slug: "couvreur-toiture-corse-du-sud-2a", region: "Corse", prefecture: "Ajaccio", villesPrincipales: ["Ajaccio", "Porto-Vecchio", "Propriano", "Sartene", "Bonifacio"], climat: "mediterraneen", toitureDominante: "tuile canal et lauze de schiste", description: "En Corse-du-Sud, le soleil intense et les vents marins imposent des toitures en tuile canal ou lauze de schiste resistantes." },
  { code: "2B", nom: "Haute-Corse", slug: "couvreur-toiture-haute-corse-2b", region: "Corse", prefecture: "Bastia", villesPrincipales: ["Bastia", "Corte", "Calvi", "Borgo", "Biguglia"], climat: "mediterraneen montagnard", toitureDominante: "tuile canal et lauze", description: "En Haute-Corse, entre littoral et montagne, les toitures subissent des conditions variees allant du sel marin a la neige." },
  { code: "21", nom: "Cote-d'Or", slug: "couvreur-toiture-cote-dor-21", region: "Bourgogne-Franche-Comte", prefecture: "Dijon", villesPrincipales: ["Dijon", "Beaune", "Chenove", "Talant", "Auxonne"], climat: "semi-continental", toitureDominante: "tuile vernissee bourguignonne et tuile plate", description: "En Cote-d'Or, les celebres tuiles vernissees bourguignonnes necessitent un entretien specifique face au gel et aux pluies." },
  { code: "22", nom: "Cotes-d'Armor", slug: "couvreur-toiture-cotes-darmor-22", region: "Bretagne", prefecture: "Saint-Brieuc", villesPrincipales: ["Saint-Brieuc", "Lannion", "Dinan", "Lamballe-Armor", "Ploufragan"], climat: "oceanique", toitureDominante: "ardoise bretonne", description: "Dans les Cotes-d'Armor, les vents du large et l'humidite permanente favorisent la mousse sur les toitures en ardoise bretonne." },
  { code: "23", nom: "Creuse", slug: "couvreur-toiture-creuse-23", region: "Nouvelle-Aquitaine", prefecture: "Gueret", villesPrincipales: ["Gueret", "La Souterraine", "Aubusson", "Sainte-Feyre", "Bourganeuf"], climat: "oceanique degrade", toitureDominante: "ardoise et tuile plate", description: "Dans la Creuse, les hivers froids du plateau de Millevaches et l'humidite fragilisent les toitures en ardoise." },
  { code: "24", nom: "Dordogne", slug: "couvreur-toiture-dordogne-24", region: "Nouvelle-Aquitaine", prefecture: "Perigueux", villesPrincipales: ["Perigueux", "Bergerac", "Sarlat-la-Caneda", "Coulounieix-Chamiers", "Trelissac"], climat: "oceanique altere", toitureDominante: "tuile plate et lauze", description: "En Dordogne, les toitures en lauze du Perigord et tuile plate sont soumises aux pluies regulieres et a l'humidite ambiante." },
  { code: "25", nom: "Doubs", slug: "couvreur-toiture-doubs-25", region: "Bourgogne-Franche-Comte", prefecture: "Besancon", villesPrincipales: ["Besancon", "Montbeliard", "Pontarlier", "Audincourt", "Valentigney"], climat: "continental a montagnard", toitureDominante: "tuile mecanique et tavillon", description: "Dans le Doubs, les hivers rigoureux du Jura et les fortes chutes de neige exigent des toitures robustes et bien isolees." },
  { code: "26", nom: "Drome", slug: "couvreur-toiture-drome-26", region: "Auvergne-Rhone-Alpes", prefecture: "Valence", villesPrincipales: ["Valence", "Montelimar", "Romans-sur-Isere", "Bourg-les-Valence", "Pierrelatte"], climat: "mediterraneen a semi-continental", toitureDominante: "tuile canal et tuile romane", description: "Dans la Drome, la transition entre climats mediterraneen et continental soumet les toitures a des contraintes thermiques variees." },
  { code: "27", nom: "Eure", slug: "couvreur-toiture-eure-27", region: "Normandie", prefecture: "Evreux", villesPrincipales: ["Evreux", "Vernon", "Louviers", "Val-de-Reuil", "Gisors"], climat: "oceanique", toitureDominante: "ardoise et tuile plate normande", description: "Dans l'Eure, le climat normand humide et les pluies frequentes favorisent le developpement de vegetation sur les toitures." },
  { code: "28", nom: "Eure-et-Loir", slug: "couvreur-toiture-eure-et-loir-28", region: "Centre-Val de Loire", prefecture: "Chartres", villesPrincipales: ["Chartres", "Dreux", "Luce", "Mainvilliers", "Nogent-le-Rotrou"], climat: "oceanique degrade", toitureDominante: "ardoise et tuile plate de Beauce", description: "En Eure-et-Loir, les vents de la plaine de Beauce et les pluies regulieres imposent un entretien regulier des toitures." },
  { code: "29", nom: "Finistere", slug: "couvreur-toiture-finistere-29", region: "Bretagne", prefecture: "Quimper", villesPrincipales: ["Brest", "Quimper", "Morlaix", "Concarneau", "Douarnenez"], climat: "oceanique", toitureDominante: "ardoise bretonne", description: "Dans le Finistere, les tempetes atlantiques et l'air salin sont les premiers ennemis des toitures en ardoise." },
  { code: "30", nom: "Gard", slug: "couvreur-toiture-gard-30", region: "Occitanie", prefecture: "Nimes", villesPrincipales: ["Nimes", "Ales", "Bagnols-sur-Ceze", "Beaucaire", "Villeneuve-les-Avignon"], climat: "mediterraneen", toitureDominante: "tuile canal et tuile romane", description: "Dans le Gard, les episodes cevenols violents et le soleil ardent mettent a rude epreuve les toitures en tuile canal." },
  { code: "31", nom: "Haute-Garonne", slug: "couvreur-toiture-haute-garonne-31", region: "Occitanie", prefecture: "Toulouse", villesPrincipales: ["Toulouse", "Colomiers", "Tournefeuille", "Blagnac", "Muret"], climat: "oceanique a mediterraneen", toitureDominante: "tuile canal toulousaine", description: "En Haute-Garonne, la tuile canal toulousaine est emblematique mais sensible au vent d'autan et aux orages estivaux." },
  { code: "32", nom: "Gers", slug: "couvreur-toiture-gers-32", region: "Occitanie", prefecture: "Auch", villesPrincipales: ["Auch", "Condom", "Fleurance", "Lectoure", "L'Isle-Jourdain"], climat: "oceanique altere", toitureDominante: "tuile canal gasconne", description: "Dans le Gers, les toitures en tuile canal des bastides gasconnes demandent un suivi face aux intemperies du Sud-Ouest." },
  { code: "33", nom: "Gironde", slug: "couvreur-toiture-gironde-33", region: "Nouvelle-Aquitaine", prefecture: "Bordeaux", villesPrincipales: ["Bordeaux", "Merignac", "Pessac", "Talence", "Villenave-d'Ornon"], climat: "oceanique", toitureDominante: "tuile canal et tuile mecanique", description: "En Gironde, l'humidite atlantique et les tempetes hivernales degradent les toitures bordelaises en tuile canal." },
  { code: "34", nom: "Herault", slug: "couvreur-toiture-herault-34", region: "Occitanie", prefecture: "Montpellier", villesPrincipales: ["Montpellier", "Beziers", "Sete", "Agde", "Lunel"], climat: "mediterraneen", toitureDominante: "tuile canal et tuile romane", description: "Dans l'Herault, les toitures en tuile romane subissent les effets de la tramontane et les orages mediterraneens violents." },
  { code: "35", nom: "Ille-et-Vilaine", slug: "couvreur-toiture-ille-et-vilaine-35", region: "Bretagne", prefecture: "Rennes", villesPrincipales: ["Rennes", "Saint-Malo", "Fougeres", "Vitre", "Cesson-Sevigne"], climat: "oceanique", toitureDominante: "ardoise bretonne", description: "En Ille-et-Vilaine, les toitures en ardoise bretonne sont exposees aux pluies frequentes et a l'humidite permanente." },
  { code: "36", nom: "Indre", slug: "couvreur-toiture-indre-36", region: "Centre-Val de Loire", prefecture: "Chateauroux", villesPrincipales: ["Chateauroux", "Issoudun", "Deols", "Le Blanc", "Argenton-sur-Creuse"], climat: "oceanique degrade", toitureDominante: "tuile plate et ardoise", description: "Dans l'Indre, les toitures en tuile plate du Berry necessitent un entretien face aux gelees et pluies regulieres." },
  { code: "37", nom: "Indre-et-Loire", slug: "couvreur-toiture-indre-et-loire-37", region: "Centre-Val de Loire", prefecture: "Tours", villesPrincipales: ["Tours", "Joue-les-Tours", "Saint-Avertin", "Saint-Cyr-sur-Loire", "Amboise"], climat: "oceanique degrade", toitureDominante: "ardoise de Touraine et tuile plate", description: "En Indre-et-Loire, les toitures en ardoise de Touraine sont un patrimoine a proteger face a l'humidite du Val de Loire." },
  { code: "38", nom: "Isere", slug: "couvreur-toiture-isere-38", region: "Auvergne-Rhone-Alpes", prefecture: "Grenoble", villesPrincipales: ["Grenoble", "Saint-Martin-d'Heres", "Echirolles", "Vienne", "Voiron"], climat: "semi-continental a montagnard", toitureDominante: "tuile mecanique et ardoise", description: "En Isere, entre Alpes et plaine du Gresivaudan, les toitures doivent resister aux chutes de neige et aux ecarts thermiques." },
  { code: "39", nom: "Jura", slug: "couvreur-toiture-jura-39", region: "Bourgogne-Franche-Comte", prefecture: "Lons-le-Saunier", villesPrincipales: ["Lons-le-Saunier", "Dole", "Saint-Claude", "Champagnole", "Morez"], climat: "continental a montagnard", toitureDominante: "tuile mecanique et tavillon", description: "Dans le Jura, l'altitude et les hivers enneiges imposent des toitures a forte pente capables d'evacuer la neige." },
  { code: "40", nom: "Landes", slug: "couvreur-toiture-landes-40", region: "Nouvelle-Aquitaine", prefecture: "Mont-de-Marsan", villesPrincipales: ["Mont-de-Marsan", "Dax", "Biscarrosse", "Saint-Paul-les-Dax", "Tarnos"], climat: "oceanique", toitureDominante: "tuile canal landaise et tuile mecanique", description: "Dans les Landes, l'humidite de la foret et les tempetes atlantiques exigent des toitures bien entretenues." },
  { code: "41", nom: "Loir-et-Cher", slug: "couvreur-toiture-loir-et-cher-41", region: "Centre-Val de Loire", prefecture: "Blois", villesPrincipales: ["Blois", "Vendome", "Romorantin-Lanthenay", "Vineuil", "Mer"], climat: "oceanique degrade", toitureDominante: "ardoise et tuile plate", description: "En Loir-et-Cher, les toitures des chateaux et demeures du Val de Loire en ardoise necessitent un savoir-faire d'expert." },
  { code: "42", nom: "Loire", slug: "couvreur-toiture-loire-42", region: "Auvergne-Rhone-Alpes", prefecture: "Saint-Etienne", villesPrincipales: ["Saint-Etienne", "Roanne", "Saint-Chamond", "Firminy", "Montbrison"], climat: "semi-continental", toitureDominante: "tuile mecanique et ardoise", description: "Dans la Loire, les hivers froids du Massif central et les precipitations abondantes fragilisent les toitures stephanoisennes." },
  { code: "43", nom: "Haute-Loire", slug: "couvreur-toiture-haute-loire-43", region: "Auvergne-Rhone-Alpes", prefecture: "Le Puy-en-Velay", villesPrincipales: ["Le Puy-en-Velay", "Monistrol-sur-Loire", "Brioude", "Yssingeaux", "Sainte-Sigolene"], climat: "montagnard", toitureDominante: "lauze et tuile mecanique", description: "En Haute-Loire, les toitures en lauze volcanique du Velay subissent les rigueurs de l'hiver auvergnat." },
  { code: "44", nom: "Loire-Atlantique", slug: "couvreur-toiture-loire-atlantique-44", region: "Pays de la Loire", prefecture: "Nantes", villesPrincipales: ["Nantes", "Saint-Nazaire", "Reze", "Saint-Herblain", "Orvault"], climat: "oceanique", toitureDominante: "ardoise et zinc", description: "En Loire-Atlantique, le climat atlantique humide impose un entretien regulier des toitures en ardoise nantaises." },
  { code: "45", nom: "Loiret", slug: "couvreur-toiture-loiret-45", region: "Centre-Val de Loire", prefecture: "Orleans", villesPrincipales: ["Orleans", "Olivet", "Saint-Jean-de-Braye", "Fleury-les-Aubrais", "Saran"], climat: "oceanique degrade", toitureDominante: "tuile plate et ardoise", description: "Dans le Loiret, les toitures en tuile plate de la Beauce et ardoise du Val de Loire demandent une surveillance reguliere." },
  { code: "46", nom: "Lot", slug: "couvreur-toiture-lot-46", region: "Occitanie", prefecture: "Cahors", villesPrincipales: ["Cahors", "Figeac", "Gourdon", "Souillac", "Gramat"], climat: "oceanique altere", toitureDominante: "tuile plate du Quercy et lauze", description: "Dans le Lot, les toitures en tuile plate du Quercy et les lauzes traditionnelles des causses sont un patrimoine a preserver." },
  { code: "47", nom: "Lot-et-Garonne", slug: "couvreur-toiture-lot-et-garonne-47", region: "Nouvelle-Aquitaine", prefecture: "Agen", villesPrincipales: ["Agen", "Villeneuve-sur-Lot", "Marmande", "Le Passage", "Tonneins"], climat: "oceanique altere", toitureDominante: "tuile canal et tuile mecanique", description: "En Lot-et-Garonne, les orages d'ete et l'humidite degradent les toitures en tuile canal des bastides du Sud-Ouest." },
  { code: "48", nom: "Lozere", slug: "couvreur-toiture-lozere-48", region: "Occitanie", prefecture: "Mende", villesPrincipales: ["Mende", "Marvejols", "Saint-Chely-d'Apcher", "Langogne", "Florac-Trois-Rivieres"], climat: "montagnard", toitureDominante: "lauze et ardoise", description: "En Lozere, les toitures en lauze des Causses et Cevennes resistent depuis des siecles mais demandent un savoir-faire specifique." },
  { code: "49", nom: "Maine-et-Loire", slug: "couvreur-toiture-maine-et-loire-49", region: "Pays de la Loire", prefecture: "Angers", villesPrincipales: ["Angers", "Cholet", "Saumur", "Avrille", "Les Ponts-de-Ce"], climat: "oceanique", toitureDominante: "ardoise d'Angers et tuile plate", description: "En Maine-et-Loire, l'ardoise d'Angers est un materiau emblematique dont l'entretien est essentiel face au climat atlantique." },
  { code: "50", nom: "Manche", slug: "couvreur-toiture-manche-50", region: "Normandie", prefecture: "Saint-Lo", villesPrincipales: ["Cherbourg-en-Cotentin", "Saint-Lo", "Granville", "Coutances", "Valognes"], climat: "oceanique", toitureDominante: "ardoise et granite", description: "Dans la Manche, les tempetes de la cote normande et les vents violents imposent des toitures en ardoise extremement solides." },
  { code: "51", nom: "Marne", slug: "couvreur-toiture-marne-51", region: "Grand Est", prefecture: "Chalons-en-Champagne", villesPrincipales: ["Reims", "Chalons-en-Champagne", "Epernay", "Vitry-le-Francois", "Tinqueux"], climat: "continental", toitureDominante: "tuile plate champenoise et ardoise", description: "Dans la Marne, le gel hivernal et les precipitations regulieres fragilisent les toitures en tuile plate champenoise." },
  { code: "52", nom: "Haute-Marne", slug: "couvreur-toiture-haute-marne-52", region: "Grand Est", prefecture: "Chaumont", villesPrincipales: ["Saint-Dizier", "Chaumont", "Langres", "Joinville", "Nogent"], climat: "continental", toitureDominante: "tuile plate et ardoise", description: "En Haute-Marne, les hivers rigoureux du plateau de Langres mettent a l'epreuve les couvertures traditionnelles." },
  { code: "53", nom: "Mayenne", slug: "couvreur-toiture-mayenne-53", region: "Pays de la Loire", prefecture: "Laval", villesPrincipales: ["Laval", "Mayenne", "Chateau-Gontier-sur-Mayenne", "Evron", "Bonchamp-les-Laval"], climat: "oceanique", toitureDominante: "ardoise et tuile plate", description: "En Mayenne, le climat oceanique doux mais humide favorise la vegetation parasite sur les toitures en ardoise." },
  { code: "54", nom: "Meurthe-et-Moselle", slug: "couvreur-toiture-meurthe-et-moselle-54", region: "Grand Est", prefecture: "Nancy", villesPrincipales: ["Nancy", "Vandoeuvre-les-Nancy", "Luneville", "Toul", "Villers-les-Nancy"], climat: "continental", toitureDominante: "tuile mecanique et ardoise", description: "En Meurthe-et-Moselle, les hivers froids et neigeux du Grand Est imposent des toitures robustes et bien isolees." },
  { code: "55", nom: "Meuse", slug: "couvreur-toiture-meuse-55", region: "Grand Est", prefecture: "Bar-le-Duc", villesPrincipales: ["Verdun", "Bar-le-Duc", "Commercy", "Saint-Mihiel", "Etain"], climat: "continental", toitureDominante: "tuile mecanique et tuile plate", description: "Dans la Meuse, les rigueurs climatiques continentales necessitent un suivi attentif des toitures traditionnelles." },
  { code: "56", nom: "Morbihan", slug: "couvreur-toiture-morbihan-56", region: "Bretagne", prefecture: "Vannes", villesPrincipales: ["Vannes", "Lorient", "Lanester", "Pontivy", "Hennebont"], climat: "oceanique", toitureDominante: "ardoise bretonne", description: "Dans le Morbihan, les embruns et les tempetes du Golfe fragilisent les toitures en ardoise bretonne traditionnelles." },
  { code: "57", nom: "Moselle", slug: "couvreur-toiture-moselle-57", region: "Grand Est", prefecture: "Metz", villesPrincipales: ["Metz", "Thionville", "Forbach", "Sarreguemines", "Montigny-les-Metz"], climat: "continental", toitureDominante: "tuile mecanique et ardoise", description: "En Moselle, les ecarts de temperature entre ete et hiver et les precipitations abondantes usent les toitures rapidement." },
  { code: "58", nom: "Nievre", slug: "couvreur-toiture-nievre-58", region: "Bourgogne-Franche-Comte", prefecture: "Nevers", villesPrincipales: ["Nevers", "Cosne-Cours-sur-Loire", "Varennes-Vauzelles", "Decize", "La Charite-sur-Loire"], climat: "oceanique degrade", toitureDominante: "tuile plate bourguignonne et ardoise", description: "Dans la Nievre, les toitures en tuile bourguignonne subissent les effets du gel et de l'humidite du Morvan." },
  { code: "59", nom: "Nord", slug: "couvreur-toiture-nord-59", region: "Hauts-de-France", prefecture: "Lille", villesPrincipales: ["Lille", "Roubaix", "Tourcoing", "Dunkerque", "Villeneuve-d'Ascq"], climat: "oceanique", toitureDominante: "tuile du nord et ardoise", description: "Dans le Nord, les pluies frequentes et le vent du large sur le littoral favorisent la degradation des toitures en tuile." },
  { code: "60", nom: "Oise", slug: "couvreur-toiture-oise-60", region: "Hauts-de-France", prefecture: "Beauvais", villesPrincipales: ["Beauvais", "Compiegne", "Creil", "Nogent-sur-Oise", "Senlis"], climat: "oceanique degrade", toitureDominante: "tuile plate et ardoise", description: "Dans l'Oise, les toitures en tuile plate des villages picards necessitent un entretien regulier face a l'humidite." },
  { code: "61", nom: "Orne", slug: "couvreur-toiture-orne-61", region: "Normandie", prefecture: "Alencon", villesPrincipales: ["Alencon", "Flers", "Argentan", "L'Aigle", "Mortagne-au-Perche"], climat: "oceanique", toitureDominante: "ardoise et tuile plate normande", description: "Dans l'Orne, notre departement d'implantation, nous connaissons parfaitement les toitures normandes en ardoise et tuile plate soumises au climat oceanique humide." },
  { code: "62", nom: "Pas-de-Calais", slug: "couvreur-toiture-pas-de-calais-62", region: "Hauts-de-France", prefecture: "Arras", villesPrincipales: ["Calais", "Boulogne-sur-Mer", "Arras", "Lens", "Lievin"], climat: "oceanique", toitureDominante: "tuile du nord et ardoise", description: "Dans le Pas-de-Calais, les vents du littoral et les pluies frequentes exercent une pression constante sur les toitures." },
  { code: "63", nom: "Puy-de-Dome", slug: "couvreur-toiture-puy-de-dome-63", region: "Auvergne-Rhone-Alpes", prefecture: "Clermont-Ferrand", villesPrincipales: ["Clermont-Ferrand", "Cournon-d'Auvergne", "Riom", "Chamalieres", "Issoire"], climat: "semi-continental a montagnard", toitureDominante: "tuile mecanique et lauze volcanique", description: "Dans le Puy-de-Dome, les toitures en lauze volcanique et tuile mecanique doivent resister aux hivers auvergnats." },
  { code: "64", nom: "Pyrenees-Atlantiques", slug: "couvreur-toiture-pyrenees-atlantiques-64", region: "Nouvelle-Aquitaine", prefecture: "Pau", villesPrincipales: ["Pau", "Bayonne", "Anglet", "Biarritz", "Hendaye"], climat: "oceanique a montagnard", toitureDominante: "ardoise et tuile canal", description: "Dans les Pyrenees-Atlantiques, entre cote basque et montagnes, les toitures subissent pluies intenses et neige." },
  { code: "65", nom: "Hautes-Pyrenees", slug: "couvreur-toiture-hautes-pyrenees-65", region: "Occitanie", prefecture: "Tarbes", villesPrincipales: ["Tarbes", "Lourdes", "Bagneres-de-Bigorre", "Aureilhan", "Vic-en-Bigorre"], climat: "montagnard a oceanique", toitureDominante: "ardoise pyreneenne", description: "Dans les Hautes-Pyrenees, les chutes de neige importantes et les vents de montagne exigent des toitures en ardoise solides." },
  { code: "66", nom: "Pyrenees-Orientales", slug: "couvreur-toiture-pyrenees-orientales-66", region: "Occitanie", prefecture: "Perpignan", villesPrincipales: ["Perpignan", "Canet-en-Roussillon", "Saint-Esteve", "Rivesaltes", "Pia"], climat: "mediterraneen", toitureDominante: "tuile canal catalane", description: "Dans les Pyrenees-Orientales, la tramontane violente et le soleil intense mettent a l'epreuve les tuiles canal catalanes." },
  { code: "67", nom: "Bas-Rhin", slug: "couvreur-toiture-bas-rhin-67", region: "Grand Est", prefecture: "Strasbourg", villesPrincipales: ["Strasbourg", "Haguenau", "Schiltigheim", "Illkirch-Graffenstaden", "Lingolsheim"], climat: "continental", toitureDominante: "tuile plate alsacienne et tuile biberschwanz", description: "Dans le Bas-Rhin, les toitures alsaciennes en tuile plate traditionnelle resistent depuis des siecles aux hivers rigoureux." },
  { code: "68", nom: "Haut-Rhin", slug: "couvreur-toiture-haut-rhin-68", region: "Grand Est", prefecture: "Colmar", villesPrincipales: ["Mulhouse", "Colmar", "Saint-Louis", "Illzach", "Wittenheim"], climat: "continental", toitureDominante: "tuile plate alsacienne", description: "Dans le Haut-Rhin, entre plaine d'Alsace et Vosges, les toitures traditionnelles necessitent un entretien face au gel et a la neige." },
  { code: "69", nom: "Rhone", slug: "couvreur-toiture-rhone-69", region: "Auvergne-Rhone-Alpes", prefecture: "Lyon", villesPrincipales: ["Lyon", "Villeurbanne", "Venissieux", "Vaulx-en-Velin", "Saint-Priest"], climat: "semi-continental", toitureDominante: "tuile mecanique et tuile canal", description: "Dans le Rhone, les toitures lyonnaises subissent des etés chauds et des hivers froids avec des precipitations regulieres." },
  { code: "70", nom: "Haute-Saone", slug: "couvreur-toiture-haute-saone-70", region: "Bourgogne-Franche-Comte", prefecture: "Vesoul", villesPrincipales: ["Vesoul", "Hericourt", "Lure", "Luxeuil-les-Bains", "Gray"], climat: "continental", toitureDominante: "tuile mecanique et tuile plate", description: "En Haute-Saone, les hivers froids de Franche-Comte et l'humidite fragilisent les toitures des villages traditionnels." },
  { code: "71", nom: "Saone-et-Loire", slug: "couvreur-toiture-saone-et-loire-71", region: "Bourgogne-Franche-Comte", prefecture: "Macon", villesPrincipales: ["Chalon-sur-Saone", "Macon", "Le Creusot", "Montceau-les-Mines", "Autun"], climat: "semi-continental", toitureDominante: "tuile bourguignonne vernissee", description: "En Saone-et-Loire, les celebres tuiles vernissees multicolores de Bourgogne demandent un savoir-faire d'entretien specifique." },
  { code: "72", nom: "Sarthe", slug: "couvreur-toiture-sarthe-72", region: "Pays de la Loire", prefecture: "Le Mans", villesPrincipales: ["Le Mans", "La Fleche", "Allonnes", "Sable-sur-Sarthe", "Coulaines"], climat: "oceanique", toitureDominante: "ardoise et tuile plate", description: "Dans la Sarthe, le climat doux mais humide de la region mancelle favorise le developpement de mousses sur les toitures." },
  { code: "73", nom: "Savoie", slug: "couvreur-toiture-savoie-73", region: "Auvergne-Rhone-Alpes", prefecture: "Chambery", villesPrincipales: ["Chambery", "Aix-les-Bains", "Albertville", "Saint-Jean-de-Maurienne", "La Motte-Servolex"], climat: "montagnard", toitureDominante: "lauze et bac acier", description: "En Savoie, les fortes chutes de neige et les temperatures negatives imposent des toitures a tres forte pente." },
  { code: "74", nom: "Haute-Savoie", slug: "couvreur-toiture-haute-savoie-74", region: "Auvergne-Rhone-Alpes", prefecture: "Annecy", villesPrincipales: ["Annecy", "Thonon-les-Bains", "Annemasse", "Cluses", "Bonneville"], climat: "montagnard", toitureDominante: "tavillon et bac acier", description: "En Haute-Savoie, les chalets traditionnels en tavillon et les toitures modernes en bac acier subissent neige et gel intenses." },
  { code: "75", nom: "Paris", slug: "couvreur-toiture-paris-75", region: "Ile-de-France", prefecture: "Paris", villesPrincipales: ["Paris 1er", "Paris 8e", "Paris 15e", "Paris 16e", "Paris 20e"], climat: "oceanique degrade", toitureDominante: "zinc et ardoise", description: "A Paris, les toitures en zinc haussmanniennes sont un patrimoine unique qui necessite des couvreurs specialises." },
  { code: "76", nom: "Seine-Maritime", slug: "couvreur-toiture-seine-maritime-76", region: "Normandie", prefecture: "Rouen", villesPrincipales: ["Le Havre", "Rouen", "Dieppe", "Sotteville-les-Rouen", "Saint-Etienne-du-Rouvray"], climat: "oceanique", toitureDominante: "ardoise et tuile plate normande", description: "En Seine-Maritime, les vents du littoral et les pluies normandes imposent un entretien regulier des toitures en ardoise." },
  { code: "77", nom: "Seine-et-Marne", slug: "couvreur-toiture-seine-et-marne-77", region: "Ile-de-France", prefecture: "Melun", villesPrincipales: ["Meaux", "Chelles", "Melun", "Pontault-Combault", "Savigny-le-Temple"], climat: "oceanique degrade", toitureDominante: "tuile plate et ardoise", description: "En Seine-et-Marne, les toitures en tuile plate d'Ile-de-France demandent un suivi face aux intemperies et au gel." },
  { code: "78", nom: "Yvelines", slug: "couvreur-toiture-yvelines-78", region: "Ile-de-France", prefecture: "Versailles", villesPrincipales: ["Versailles", "Sartrouville", "Mantes-la-Jolie", "Saint-Germain-en-Laye", "Poissy"], climat: "oceanique degrade", toitureDominante: "ardoise et tuile plate", description: "Dans les Yvelines, les toitures des demeures historiques et pavillons necessitent un entretien expert." },
  { code: "79", nom: "Deux-Sevres", slug: "couvreur-toiture-deux-sevres-79", region: "Nouvelle-Aquitaine", prefecture: "Niort", villesPrincipales: ["Niort", "Bressuire", "Parthenay", "Thouars", "Melle"], climat: "oceanique", toitureDominante: "tuile canal et tuile romane", description: "Dans les Deux-Sevres, les pluies atlantiques et le vent d'ouest fragilisent les toitures en tuile canal." },
  { code: "80", nom: "Somme", slug: "couvreur-toiture-somme-80", region: "Hauts-de-France", prefecture: "Amiens", villesPrincipales: ["Amiens", "Abbeville", "Albert", "Peronne", "Ham"], climat: "oceanique", toitureDominante: "tuile du nord et ardoise", description: "Dans la Somme, le vent du littoral picard et les pluies regulieres imposent un entretien frequent des toitures." },
  { code: "81", nom: "Tarn", slug: "couvreur-toiture-tarn-81", region: "Occitanie", prefecture: "Albi", villesPrincipales: ["Albi", "Castres", "Gaillac", "Mazamet", "Graulhet"], climat: "oceanique altere a mediterraneen", toitureDominante: "tuile canal et tuile romane", description: "Dans le Tarn, entre plaines et Montagne Noire, les toitures en tuile canal subissent vent d'autan et orages d'ete." },
  { code: "82", nom: "Tarn-et-Garonne", slug: "couvreur-toiture-tarn-et-garonne-82", region: "Occitanie", prefecture: "Montauban", villesPrincipales: ["Montauban", "Castelsarrasin", "Moissac", "Caussade", "Valence-d'Agen"], climat: "oceanique altere", toitureDominante: "tuile canal", description: "En Tarn-et-Garonne, les orages violents et la grele endommagent regulierement les toitures en tuile canal." },
  { code: "83", nom: "Var", slug: "couvreur-toiture-var-83", region: "Provence-Alpes-Cote d'Azur", prefecture: "Toulon", villesPrincipales: ["Toulon", "Frejus", "Hyeres", "Draguignan", "La Seyne-sur-Mer"], climat: "mediterraneen", toitureDominante: "tuile canal et tuile romane", description: "Dans le Var, le soleil provencal et les orages mediterraneens violents degradent les toitures en tuile canal." },
  { code: "84", nom: "Vaucluse", slug: "couvreur-toiture-vaucluse-84", region: "Provence-Alpes-Cote d'Azur", prefecture: "Avignon", villesPrincipales: ["Avignon", "Carpentras", "Orange", "Cavaillon", "L'Isle-sur-la-Sorgue"], climat: "mediterraneen", toitureDominante: "tuile canal et tuile romane", description: "Dans le Vaucluse, le mistral violent et le soleil intense sont les premiers ennemis des toitures provencales." },
  { code: "85", nom: "Vendee", slug: "couvreur-toiture-vendee-85", region: "Pays de la Loire", prefecture: "La Roche-sur-Yon", villesPrincipales: ["La Roche-sur-Yon", "Les Sables-d'Olonne", "Challans", "Les Herbiers", "Fontenay-le-Comte"], climat: "oceanique", toitureDominante: "tuile canal et tuile romane", description: "En Vendee, les tempetes atlantiques et l'air salin du littoral accelerent l'usure des toitures vendeennes." },
  { code: "86", nom: "Vienne", slug: "couvreur-toiture-vienne-86", region: "Nouvelle-Aquitaine", prefecture: "Poitiers", villesPrincipales: ["Poitiers", "Chatellerault", "Buxerolles", "Jaunay-Clan", "Migne-Auxances"], climat: "oceanique", toitureDominante: "tuile plate et tuile canal", description: "Dans la Vienne, les toitures en tuile plate du Poitou necessitent un entretien face a l'humidite atlantique." },
  { code: "87", nom: "Haute-Vienne", slug: "couvreur-toiture-haute-vienne-87", region: "Nouvelle-Aquitaine", prefecture: "Limoges", villesPrincipales: ["Limoges", "Saint-Junien", "Panazol", "Isle", "Couzeix"], climat: "oceanique degrade", toitureDominante: "tuile mecanique et ardoise", description: "En Haute-Vienne, les precipitations abondantes du Limousin favorisent le developpement de mousse sur les toitures." },
  { code: "88", nom: "Vosges", slug: "couvreur-toiture-vosges-88", region: "Grand Est", prefecture: "Epinal", villesPrincipales: ["Epinal", "Saint-Die-des-Vosges", "Gerardmer", "Remiremont", "Golbey"], climat: "continental a montagnard", toitureDominante: "tuile mecanique et gres vosgien", description: "Dans les Vosges, l'altitude et les hivers enneiges necessitent des toitures capables de supporter d'importantes charges." },
  { code: "89", nom: "Yonne", slug: "couvreur-toiture-yonne-89", region: "Bourgogne-Franche-Comte", prefecture: "Auxerre", villesPrincipales: ["Auxerre", "Sens", "Joigny", "Migennes", "Avallon"], climat: "oceanique degrade", toitureDominante: "tuile plate bourguignonne et ardoise", description: "Dans l'Yonne, les toitures en tuile plate de Bourgogne subissent gelees hivernales et pluies regulieres." },
  { code: "90", nom: "Territoire de Belfort", slug: "couvreur-toiture-territoire-belfort-90", region: "Bourgogne-Franche-Comte", prefecture: "Belfort", villesPrincipales: ["Belfort", "Delle", "Valdoie", "Beaucourt", "Bavilliers"], climat: "continental", toitureDominante: "tuile mecanique", description: "Dans le Territoire de Belfort, la Trouee de Belfort expose les toitures aux vents et aux rigueurs continentales." },
  { code: "91", nom: "Essonne", slug: "couvreur-toiture-essonne-91", region: "Ile-de-France", prefecture: "Evry-Courcouronnes", villesPrincipales: ["Evry-Courcouronnes", "Corbeil-Essonnes", "Massy", "Savigny-sur-Orge", "Sainte-Genevieve-des-Bois"], climat: "oceanique degrade", toitureDominante: "tuile plate et ardoise", description: "En Essonne, les toitures des pavillons franciliens necessitent un suivi regulier face aux intemperies." },
  { code: "92", nom: "Hauts-de-Seine", slug: "couvreur-toiture-hauts-de-seine-92", region: "Ile-de-France", prefecture: "Nanterre", villesPrincipales: ["Boulogne-Billancourt", "Nanterre", "Courbevoie", "Colombes", "Asnieres-sur-Seine"], climat: "oceanique degrade", toitureDominante: "zinc et ardoise", description: "Dans les Hauts-de-Seine, les toitures en zinc des immeubles et les ardoises des pavillons demandent un entretien expert." },
  { code: "93", nom: "Seine-Saint-Denis", slug: "couvreur-toiture-seine-saint-denis-93", region: "Ile-de-France", prefecture: "Bobigny", villesPrincipales: ["Saint-Denis", "Montreuil", "Bobigny", "Aulnay-sous-Bois", "Aubervilliers"], climat: "oceanique degrade", toitureDominante: "zinc et tuile mecanique", description: "En Seine-Saint-Denis, les toitures variees du tissu urbain dense necessitent des interventions adaptees a chaque type." },
  { code: "94", nom: "Val-de-Marne", slug: "couvreur-toiture-val-de-marne-94", region: "Ile-de-France", prefecture: "Creteil", villesPrincipales: ["Creteil", "Vitry-sur-Seine", "Saint-Maur-des-Fosses", "Champigny-sur-Marne", "Ivry-sur-Seine"], climat: "oceanique degrade", toitureDominante: "zinc et tuile plate", description: "Dans le Val-de-Marne, les toitures des zones pavillonnaires et des immeubles demandent un diagnostic precis." },
  { code: "95", nom: "Val-d'Oise", slug: "couvreur-toiture-val-doise-95", region: "Ile-de-France", prefecture: "Pontoise", villesPrincipales: ["Argenteuil", "Sarcelles", "Cergy", "Garges-les-Gonesse", "Franconville"], climat: "oceanique degrade", toitureDominante: "tuile plate et ardoise", description: "Dans le Val-d'Oise, les toitures des pavillons et maisons de ville necessitent un entretien regulier." },
  { code: "971", nom: "Guadeloupe", slug: "couvreur-toiture-guadeloupe-971", region: "Guadeloupe", prefecture: "Basse-Terre", villesPrincipales: ["Les Abymes", "Baie-Mahault", "Le Gosier", "Sainte-Anne", "Pointe-a-Pitre"], climat: "tropical", toitureDominante: "tole et bac acier", description: "En Guadeloupe, les cyclones et le climat tropical imposent des toitures en tole et bac acier extremement resistantes." },
  { code: "972", nom: "Martinique", slug: "couvreur-toiture-martinique-972", region: "Martinique", prefecture: "Fort-de-France", villesPrincipales: ["Fort-de-France", "Le Lamentin", "Le Robert", "Schoelcher", "Sainte-Marie"], climat: "tropical", toitureDominante: "tole et bac acier", description: "En Martinique, les ouragans et la chaleur tropicale necessitent des toitures en tole renforcees aux normes cycloniques." },
  { code: "973", nom: "Guyane", slug: "couvreur-toiture-guyane-973", region: "Guyane", prefecture: "Cayenne", villesPrincipales: ["Cayenne", "Matoury", "Saint-Laurent-du-Maroni", "Kourou", "Remire-Montjoly"], climat: "equatorial", toitureDominante: "tole et bac acier", description: "En Guyane, le climat equatorial avec ses pluies torrentielles et l'humidite constante degradent rapidement les toitures." },
  { code: "974", nom: "La Reunion", slug: "couvreur-toiture-reunion-974", region: "La Reunion", prefecture: "Saint-Denis", villesPrincipales: ["Saint-Denis", "Saint-Paul", "Saint-Pierre", "Le Tampon", "Saint-Andre"], climat: "tropical", toitureDominante: "tole et bardeaux", description: "A La Reunion, les cyclones tropicaux et les pluies records imposent des toitures en tole fixees aux normes cycloniques." },
  { code: "976", nom: "Mayotte", slug: "couvreur-toiture-mayotte-976", region: "Mayotte", prefecture: "Mamoudzou", villesPrincipales: ["Mamoudzou", "Koungou", "Dzaoudzi", "Dembeni", "Bandraboua"], climat: "tropical", toitureDominante: "tole et bac acier", description: "A Mayotte, les conditions tropicales et les cyclones necessitent des toitures robustes en tole et bac acier." },
]

export function getDepartmentBySlug(slug: string): Department | undefined {
  return departments.find((d) => d.slug === slug)
}

export function getAllDepartmentSlugs(): string[] {
  return departments.map((d) => d.slug)
}
