// Departments data for SEO pages

export interface DepartmentData {
  code: string
  name: string
  slug: string
  region: string
  prefecture: string
  climate: "oceanique" | "continental" | "mediterraneen" | "montagnard" | "semi-oceanique"
  mainRoofTypes: string[]
  specificProblems: string[]
  averageRoofAge: number
  population: number
}

export const departmentsData: Record<string, DepartmentData> = {
  "01": {
    code: "01",
    name: "Ain",
    slug: "ain",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Bourg-en-Bresse",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles mecaniques", "Ardoises"],
    specificProblems: ["Gel hivernal", "Neige en altitude", "Mousse"],
    averageRoofAge: 35,
    population: 650000
  },
  "02": {
    code: "02",
    name: "Aisne",
    slug: "aisne",
    region: "Hauts-de-France",
    prefecture: "Laon",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Zinc"],
    specificProblems: ["Humidite", "Vent du nord", "Mousse"],
    averageRoofAge: 45,
    population: 530000
  },
  "03": {
    code: "03",
    name: "Allier",
    slug: "allier",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Moulins",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles mecaniques", "Ardoises"],
    specificProblems: ["Variations thermiques", "Mousse", "Gel"],
    averageRoofAge: 40,
    population: 340000
  },
  "04": {
    code: "04",
    name: "Alpes-de-Haute-Provence",
    slug: "alpes-de-haute-provence",
    region: "Provence-Alpes-Cote d'Azur",
    prefecture: "Digne-les-Bains",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Lauzes"],
    specificProblems: ["Soleil intense", "Vent", "Secheresse"],
    averageRoofAge: 38,
    population: 165000
  },
  "05": {
    code: "05",
    name: "Hautes-Alpes",
    slug: "hautes-alpes",
    region: "Provence-Alpes-Cote d'Azur",
    prefecture: "Gap",
    climate: "montagnard",
    mainRoofTypes: ["Lauzes", "Ardoises", "Bac acier"],
    specificProblems: ["Neige lourde", "Gel severe", "UV intenses"],
    averageRoofAge: 35,
    population: 140000
  },
  "06": {
    code: "06",
    name: "Alpes-Maritimes",
    slug: "alpes-maritimes",
    region: "Provence-Alpes-Cote d'Azur",
    prefecture: "Nice",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Terrasses"],
    specificProblems: ["Sel marin", "Soleil intense", "Pluies torrentielles"],
    averageRoofAge: 32,
    population: 1080000
  },
  "07": {
    code: "07",
    name: "Ardeche",
    slug: "ardeche",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Privas",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Lauzes", "Ardoises"],
    specificProblems: ["Episodes cevenols", "Secheresse estivale", "Vent"],
    averageRoofAge: 42,
    population: 330000
  },
  "08": {
    code: "08",
    name: "Ardennes",
    slug: "ardennes",
    region: "Grand Est",
    prefecture: "Charleville-Mezieres",
    climate: "continental",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Zinc"],
    specificProblems: ["Gel severe", "Neige", "Humidite"],
    averageRoofAge: 48,
    population: 275000
  },
  "09": {
    code: "09",
    name: "Ariege",
    slug: "ariege",
    region: "Occitanie",
    prefecture: "Foix",
    climate: "montagnard",
    mainRoofTypes: ["Ardoises", "Lauzes", "Tuiles canal"],
    specificProblems: ["Neige", "Gel", "Pluies abondantes"],
    averageRoofAge: 45,
    population: 155000
  },
  "10": {
    code: "10",
    name: "Aube",
    slug: "aube",
    region: "Grand Est",
    prefecture: "Troyes",
    climate: "continental",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Gel", "Grele", "Variations thermiques"],
    averageRoofAge: 42,
    population: 310000
  },
  "11": {
    code: "11",
    name: "Aude",
    slug: "aude",
    region: "Occitanie",
    prefecture: "Carcassonne",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Terrasses"],
    specificProblems: ["Tramontane", "Soleil intense", "Secheresse"],
    averageRoofAge: 38,
    population: 370000
  },
  "12": {
    code: "12",
    name: "Aveyron",
    slug: "aveyron",
    region: "Occitanie",
    prefecture: "Rodez",
    climate: "semi-oceanique",
    mainRoofTypes: ["Lauzes", "Ardoises", "Tuiles canal"],
    specificProblems: ["Neige", "Vent", "Variations thermiques"],
    averageRoofAge: 50,
    population: 280000
  },
  "13": {
    code: "13",
    name: "Bouches-du-Rhone",
    slug: "bouches-du-rhone",
    region: "Provence-Alpes-Cote d'Azur",
    prefecture: "Marseille",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Terrasses"],
    specificProblems: ["Mistral", "Sel marin", "Soleil intense"],
    averageRoofAge: 35,
    population: 2020000
  },
  "14": {
    code: "14",
    name: "Calvados",
    slug: "calvados",
    region: "Normandie",
    prefecture: "Caen",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Chaume"],
    specificProblems: ["Humidite constante", "Vent marin", "Mousse"],
    averageRoofAge: 45,
    population: 695000
  },
  "15": {
    code: "15",
    name: "Cantal",
    slug: "cantal",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Aurillac",
    climate: "montagnard",
    mainRoofTypes: ["Lauzes", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Neige abondante", "Gel severe", "Vent"],
    averageRoofAge: 48,
    population: 145000
  },
  "16": {
    code: "16",
    name: "Charente",
    slug: "charente",
    region: "Nouvelle-Aquitaine",
    prefecture: "Angouleme",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Ardoises"],
    specificProblems: ["Humidite", "Mousse", "Lichen"],
    averageRoofAge: 42,
    population: 355000
  },
  "17": {
    code: "17",
    name: "Charente-Maritime",
    slug: "charente-maritime",
    region: "Nouvelle-Aquitaine",
    prefecture: "La Rochelle",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Ardoises"],
    specificProblems: ["Sel marin", "Vent atlantique", "Humidite"],
    averageRoofAge: 40,
    population: 650000
  },
  "18": {
    code: "18",
    name: "Cher",
    slug: "cher",
    region: "Centre-Val de Loire",
    prefecture: "Bourges",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Gel hivernal", "Grele", "Mousse"],
    averageRoofAge: 45,
    population: 305000
  },
  "19": {
    code: "19",
    name: "Correze",
    slug: "correze",
    region: "Nouvelle-Aquitaine",
    prefecture: "Tulle",
    climate: "semi-oceanique",
    mainRoofTypes: ["Ardoises", "Lauzes", "Tuiles mecaniques"],
    specificProblems: ["Pluies abondantes", "Mousse", "Gel"],
    averageRoofAge: 48,
    population: 240000
  },
  "21": {
    code: "21",
    name: "Cote-d'Or",
    slug: "cote-dor",
    region: "Bourgogne-Franche-Comte",
    prefecture: "Dijon",
    climate: "continental",
    mainRoofTypes: ["Tuiles vernissees", "Tuiles plates", "Ardoises"],
    specificProblems: ["Gel severe", "Grele", "Variations thermiques"],
    averageRoofAge: 45,
    population: 535000
  },
  "22": {
    code: "22",
    name: "Cotes-d'Armor",
    slug: "cotes-darmor",
    region: "Bretagne",
    prefecture: "Saint-Brieuc",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Zinc", "Tuiles plates"],
    specificProblems: ["Sel marin", "Vent violent", "Humidite permanente"],
    averageRoofAge: 42,
    population: 600000
  },
  "23": {
    code: "23",
    name: "Creuse",
    slug: "creuse",
    region: "Nouvelle-Aquitaine",
    prefecture: "Gueret",
    climate: "semi-oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles mecaniques", "Lauzes"],
    specificProblems: ["Gel", "Pluies", "Mousse"],
    averageRoofAge: 55,
    population: 118000
  },
  "24": {
    code: "24",
    name: "Dordogne",
    slug: "dordogne",
    region: "Nouvelle-Aquitaine",
    prefecture: "Perigueux",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Lauzes", "Tuiles plates"],
    specificProblems: ["Humidite", "Mousse", "Lichen"],
    averageRoofAge: 48,
    population: 415000
  },
  "25": {
    code: "25",
    name: "Doubs",
    slug: "doubs",
    region: "Bourgogne-Franche-Comte",
    prefecture: "Besancon",
    climate: "continental",
    mainRoofTypes: ["Tuiles plates", "Tavaillons", "Bac acier"],
    specificProblems: ["Neige lourde", "Gel severe", "UV montagne"],
    averageRoofAge: 40,
    population: 540000
  },
  "26": {
    code: "26",
    name: "Drome",
    slug: "drome",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Valence",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Ardoises"],
    specificProblems: ["Mistral", "Soleil intense", "Grele"],
    averageRoofAge: 38,
    population: 515000
  },
  "27": {
    code: "27",
    name: "Eure",
    slug: "eure",
    region: "Normandie",
    prefecture: "Evreux",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Chaume"],
    specificProblems: ["Humidite", "Mousse", "Vent"],
    averageRoofAge: 45,
    population: 600000
  },
  "28": {
    code: "28",
    name: "Eure-et-Loir",
    slug: "eure-et-loir",
    region: "Centre-Val de Loire",
    prefecture: "Chartres",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Grele", "Vent de plaine", "Mousse"],
    averageRoofAge: 42,
    population: 435000
  },
  "29": {
    code: "29",
    name: "Finistere",
    slug: "finistere",
    region: "Bretagne",
    prefecture: "Quimper",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Zinc", "Bac acier"],
    specificProblems: ["Tempetes", "Sel marin", "Humidite extreme"],
    averageRoofAge: 40,
    population: 910000
  },
  "30": {
    code: "30",
    name: "Gard",
    slug: "gard",
    region: "Occitanie",
    prefecture: "Nimes",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Terrasses"],
    specificProblems: ["Episodes cevenols", "Soleil intense", "Mistral"],
    averageRoofAge: 38,
    population: 745000
  },
  "31": {
    code: "31",
    name: "Haute-Garonne",
    slug: "haute-garonne",
    region: "Occitanie",
    prefecture: "Toulouse",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Terrasses"],
    specificProblems: ["Grele", "Vent d'autan", "Soleil"],
    averageRoofAge: 35,
    population: 1380000
  },
  "32": {
    code: "32",
    name: "Gers",
    slug: "gers",
    region: "Occitanie",
    prefecture: "Auch",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Ardoises"],
    specificProblems: ["Grele", "Secheresse estivale", "Vent"],
    averageRoofAge: 45,
    population: 190000
  },
  "33": {
    code: "33",
    name: "Gironde",
    slug: "gironde",
    region: "Nouvelle-Aquitaine",
    prefecture: "Bordeaux",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles mecaniques", "Ardoises"],
    specificProblems: ["Humidite", "Tempetes hivernales", "Mousse"],
    averageRoofAge: 38,
    population: 1600000
  },
  "34": {
    code: "34",
    name: "Herault",
    slug: "herault",
    region: "Occitanie",
    prefecture: "Montpellier",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Terrasses"],
    specificProblems: ["Episodes cevenols", "Tramontane", "Soleil intense"],
    averageRoofAge: 35,
    population: 1150000
  },
  "35": {
    code: "35",
    name: "Ille-et-Vilaine",
    slug: "ille-et-vilaine",
    region: "Bretagne",
    prefecture: "Rennes",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Zinc", "Tuiles plates"],
    specificProblems: ["Humidite", "Mousse", "Vent"],
    averageRoofAge: 40,
    population: 1080000
  },
  "36": {
    code: "36",
    name: "Indre",
    slug: "indre",
    region: "Centre-Val de Loire",
    prefecture: "Chateauroux",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Gel", "Grele", "Mousse"],
    averageRoofAge: 48,
    population: 220000
  },
  "37": {
    code: "37",
    name: "Indre-et-Loire",
    slug: "indre-et-loire",
    region: "Centre-Val de Loire",
    prefecture: "Tours",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Tuiles mecaniques"],
    specificProblems: ["Humidite", "Mousse", "Gel hivernal"],
    averageRoofAge: 45,
    population: 610000
  },
  "38": {
    code: "38",
    name: "Isere",
    slug: "isere",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Grenoble",
    climate: "continental",
    mainRoofTypes: ["Tuiles mecaniques", "Ardoises", "Bac acier"],
    specificProblems: ["Neige", "Gel", "Grele"],
    averageRoofAge: 38,
    population: 1260000
  },
  "39": {
    code: "39",
    name: "Jura",
    slug: "jura",
    region: "Bourgogne-Franche-Comte",
    prefecture: "Lons-le-Saunier",
    climate: "continental",
    mainRoofTypes: ["Tavaillons", "Tuiles plates", "Bac acier"],
    specificProblems: ["Neige lourde", "Gel severe", "Vent"],
    averageRoofAge: 45,
    population: 260000
  },
  "40": {
    code: "40",
    name: "Landes",
    slug: "landes",
    region: "Nouvelle-Aquitaine",
    prefecture: "Mont-de-Marsan",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles mecaniques", "Ardoises"],
    specificProblems: ["Tempetes atlantiques", "Humidite", "Sel marin"],
    averageRoofAge: 38,
    population: 410000
  },
  "41": {
    code: "41",
    name: "Loir-et-Cher",
    slug: "loir-et-cher",
    region: "Centre-Val de Loire",
    prefecture: "Blois",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Tuiles mecaniques"],
    specificProblems: ["Humidite", "Mousse", "Gel"],
    averageRoofAge: 48,
    population: 330000
  },
  "42": {
    code: "42",
    name: "Loire",
    slug: "loire",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Saint-Etienne",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles mecaniques", "Ardoises", "Tuiles canal"],
    specificProblems: ["Pollution industrielle", "Gel", "Pluies"],
    averageRoofAge: 42,
    population: 760000
  },
  "43": {
    code: "43",
    name: "Haute-Loire",
    slug: "haute-loire",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Le Puy-en-Velay",
    climate: "montagnard",
    mainRoofTypes: ["Lauzes", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Neige", "Gel severe", "Vent"],
    averageRoofAge: 50,
    population: 225000
  },
  "44": {
    code: "44",
    name: "Loire-Atlantique",
    slug: "loire-atlantique",
    region: "Pays de la Loire",
    prefecture: "Nantes",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Zinc", "Tuiles mecaniques"],
    specificProblems: ["Humidite", "Sel marin", "Tempetes"],
    averageRoofAge: 38,
    population: 1430000
  },
  "45": {
    code: "45",
    name: "Loiret",
    slug: "loiret",
    region: "Centre-Val de Loire",
    prefecture: "Orleans",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Grele", "Gel", "Mousse"],
    averageRoofAge: 42,
    population: 680000
  },
  "46": {
    code: "46",
    name: "Lot",
    slug: "lot",
    region: "Occitanie",
    prefecture: "Cahors",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles canal", "Lauzes", "Ardoises"],
    specificProblems: ["Secheresse", "Variations thermiques", "Mousse"],
    averageRoofAge: 52,
    population: 175000
  },
  "47": {
    code: "47",
    name: "Lot-et-Garonne",
    slug: "lot-et-garonne",
    region: "Nouvelle-Aquitaine",
    prefecture: "Agen",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Tuiles mecaniques"],
    specificProblems: ["Grele", "Secheresse estivale", "Mousse"],
    averageRoofAge: 45,
    population: 335000
  },
  "48": {
    code: "48",
    name: "Lozere",
    slug: "lozere",
    region: "Occitanie",
    prefecture: "Mende",
    climate: "montagnard",
    mainRoofTypes: ["Lauzes", "Ardoises", "Tuiles canal"],
    specificProblems: ["Neige", "Episodes cevenols", "Gel"],
    averageRoofAge: 55,
    population: 77000
  },
  "49": {
    code: "49",
    name: "Maine-et-Loire",
    slug: "maine-et-loire",
    region: "Pays de la Loire",
    prefecture: "Angers",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Zinc"],
    specificProblems: ["Humidite", "Mousse", "Vent"],
    averageRoofAge: 45,
    population: 820000
  },
  "50": {
    code: "50",
    name: "Manche",
    slug: "manche",
    region: "Normandie",
    prefecture: "Saint-Lo",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Zinc", "Chaume"],
    specificProblems: ["Tempetes", "Sel marin", "Humidite extreme"],
    averageRoofAge: 45,
    population: 500000
  },
  "51": {
    code: "51",
    name: "Marne",
    slug: "marne",
    region: "Grand Est",
    prefecture: "Chalons-en-Champagne",
    climate: "continental",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Gel", "Grele", "Variations thermiques"],
    averageRoofAge: 42,
    population: 570000
  },
  "52": {
    code: "52",
    name: "Haute-Marne",
    slug: "haute-marne",
    region: "Grand Est",
    prefecture: "Chaumont",
    climate: "continental",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Gel severe", "Neige", "Grele"],
    averageRoofAge: 50,
    population: 175000
  },
  "53": {
    code: "53",
    name: "Mayenne",
    slug: "mayenne",
    region: "Pays de la Loire",
    prefecture: "Laval",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Zinc"],
    specificProblems: ["Humidite", "Mousse", "Gel leger"],
    averageRoofAge: 48,
    population: 310000
  },
  "54": {
    code: "54",
    name: "Meurthe-et-Moselle",
    slug: "meurthe-et-moselle",
    region: "Grand Est",
    prefecture: "Nancy",
    climate: "continental",
    mainRoofTypes: ["Tuiles mecaniques", "Ardoises", "Zinc"],
    specificProblems: ["Gel", "Neige", "Pollution"],
    averageRoofAge: 45,
    population: 735000
  },
  "55": {
    code: "55",
    name: "Meuse",
    slug: "meuse",
    region: "Grand Est",
    prefecture: "Bar-le-Duc",
    climate: "continental",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Gel severe", "Neige", "Humidite"],
    averageRoofAge: 52,
    population: 185000
  },
  "56": {
    code: "56",
    name: "Morbihan",
    slug: "morbihan",
    region: "Bretagne",
    prefecture: "Vannes",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Zinc", "Tuiles plates"],
    specificProblems: ["Sel marin", "Tempetes", "Humidite"],
    averageRoofAge: 42,
    population: 760000
  },
  "57": {
    code: "57",
    name: "Moselle",
    slug: "moselle",
    region: "Grand Est",
    prefecture: "Metz",
    climate: "continental",
    mainRoofTypes: ["Tuiles mecaniques", "Ardoises", "Tuiles plates"],
    specificProblems: ["Gel", "Neige", "Pollution industrielle"],
    averageRoofAge: 45,
    population: 1045000
  },
  "58": {
    code: "58",
    name: "Nievre",
    slug: "nievre",
    region: "Bourgogne-Franche-Comte",
    prefecture: "Nevers",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Gel", "Mousse", "Variations thermiques"],
    averageRoofAge: 52,
    population: 205000
  },
  "59": {
    code: "59",
    name: "Nord",
    slug: "nord",
    region: "Hauts-de-France",
    prefecture: "Lille",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles mecaniques", "Ardoises", "Zinc"],
    specificProblems: ["Humidite", "Pollution", "Mousse"],
    averageRoofAge: 45,
    population: 2605000
  },
  "60": {
    code: "60",
    name: "Oise",
    slug: "oise",
    region: "Hauts-de-France",
    prefecture: "Beauvais",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Humidite", "Mousse", "Grele"],
    averageRoofAge: 42,
    population: 825000
  },
  "61": {
    code: "61",
    name: "Orne",
    slug: "orne",
    region: "Normandie",
    prefecture: "Alencon",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Chaume"],
    specificProblems: ["Humidite", "Mousse", "Gel hivernal"],
    averageRoofAge: 50,
    population: 280000
  },
  "62": {
    code: "62",
    name: "Pas-de-Calais",
    slug: "pas-de-calais",
    region: "Hauts-de-France",
    prefecture: "Arras",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles mecaniques", "Ardoises", "Bac acier"],
    specificProblems: ["Sel marin", "Tempetes", "Humidite"],
    averageRoofAge: 45,
    population: 1470000
  },
  "63": {
    code: "63",
    name: "Puy-de-Dome",
    slug: "puy-de-dome",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Clermont-Ferrand",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles mecaniques", "Ardoises", "Lauzes"],
    specificProblems: ["Neige", "Gel", "Vent"],
    averageRoofAge: 42,
    population: 660000
  },
  "64": {
    code: "64",
    name: "Pyrenees-Atlantiques",
    slug: "pyrenees-atlantiques",
    region: "Nouvelle-Aquitaine",
    prefecture: "Pau",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Ardoises", "Tuiles mecaniques"],
    specificProblems: ["Pluies abondantes", "Neige en montagne", "Mousse"],
    averageRoofAge: 40,
    population: 680000
  },
  "65": {
    code: "65",
    name: "Hautes-Pyrenees",
    slug: "hautes-pyrenees",
    region: "Occitanie",
    prefecture: "Tarbes",
    climate: "montagnard",
    mainRoofTypes: ["Ardoises", "Lauzes", "Bac acier"],
    specificProblems: ["Neige lourde", "Gel", "Vent de montagne"],
    averageRoofAge: 45,
    population: 230000
  },
  "66": {
    code: "66",
    name: "Pyrenees-Orientales",
    slug: "pyrenees-orientales",
    region: "Occitanie",
    prefecture: "Perpignan",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Terrasses"],
    specificProblems: ["Tramontane violente", "Soleil intense", "Secheresse"],
    averageRoofAge: 38,
    population: 480000
  },
  "67": {
    code: "67",
    name: "Bas-Rhin",
    slug: "bas-rhin",
    region: "Grand Est",
    prefecture: "Strasbourg",
    climate: "continental",
    mainRoofTypes: ["Tuiles plates", "Tuiles mecaniques", "Ardoises"],
    specificProblems: ["Gel severe", "Neige", "Grele"],
    averageRoofAge: 42,
    population: 1140000
  },
  "68": {
    code: "68",
    name: "Haut-Rhin",
    slug: "haut-rhin",
    region: "Grand Est",
    prefecture: "Colmar",
    climate: "continental",
    mainRoofTypes: ["Tuiles plates", "Tuiles mecaniques", "Ardoises"],
    specificProblems: ["Gel severe", "Neige", "Vent"],
    averageRoofAge: 42,
    population: 765000
  },
  "69": {
    code: "69",
    name: "Rhone",
    slug: "rhone",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Lyon",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles mecaniques", "Tuiles canal", "Zinc"],
    specificProblems: ["Pollution urbaine", "Grele", "Variations thermiques"],
    averageRoofAge: 38,
    population: 1860000
  },
  "70": {
    code: "70",
    name: "Haute-Saone",
    slug: "haute-saone",
    region: "Bourgogne-Franche-Comte",
    prefecture: "Vesoul",
    climate: "continental",
    mainRoofTypes: ["Tuiles plates", "Tuiles mecaniques", "Ardoises"],
    specificProblems: ["Gel", "Neige", "Humidite"],
    averageRoofAge: 48,
    population: 235000
  },
  "71": {
    code: "71",
    name: "Saone-et-Loire",
    slug: "saone-et-loire",
    region: "Bourgogne-Franche-Comte",
    prefecture: "Macon",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles plates", "Ardoises"],
    specificProblems: ["Gel", "Grele", "Mousse"],
    averageRoofAge: 45,
    population: 555000
  },
  "72": {
    code: "72",
    name: "Sarthe",
    slug: "sarthe",
    region: "Pays de la Loire",
    prefecture: "Le Mans",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Tuiles mecaniques"],
    specificProblems: ["Humidite", "Mousse", "Gel hivernal"],
    averageRoofAge: 45,
    population: 570000
  },
  "73": {
    code: "73",
    name: "Savoie",
    slug: "savoie",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Chambery",
    climate: "montagnard",
    mainRoofTypes: ["Lauzes", "Ardoises", "Bac acier"],
    specificProblems: ["Neige tres lourde", "Gel severe", "UV montagne"],
    averageRoofAge: 35,
    population: 435000
  },
  "74": {
    code: "74",
    name: "Haute-Savoie",
    slug: "haute-savoie",
    region: "Auvergne-Rhone-Alpes",
    prefecture: "Annecy",
    climate: "montagnard",
    mainRoofTypes: ["Lauzes", "Tavaillons", "Bac acier"],
    specificProblems: ["Neige abondante", "Gel", "Avalanches de toit"],
    averageRoofAge: 32,
    population: 830000
  },
  "75": {
    code: "75",
    name: "Paris",
    slug: "paris",
    region: "Ile-de-France",
    prefecture: "Paris",
    climate: "oceanique",
    mainRoofTypes: ["Zinc", "Ardoises", "Terrasses"],
    specificProblems: ["Pollution", "Pigeons", "Etancheite terrasses"],
    averageRoofAge: 85,
    population: 2160000
  },
  "76": {
    code: "76",
    name: "Seine-Maritime",
    slug: "seine-maritime",
    region: "Normandie",
    prefecture: "Rouen",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles plates", "Zinc"],
    specificProblems: ["Humidite extreme", "Sel marin", "Tempetes"],
    averageRoofAge: 48,
    population: 1260000
  },
  "77": {
    code: "77",
    name: "Seine-et-Marne",
    slug: "seine-et-marne",
    region: "Ile-de-France",
    prefecture: "Melun",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles plates", "Tuiles mecaniques", "Ardoises"],
    specificProblems: ["Grele", "Mousse", "Variations thermiques"],
    averageRoofAge: 35,
    population: 1420000
  },
  "78": {
    code: "78",
    name: "Yvelines",
    slug: "yvelines",
    region: "Ile-de-France",
    prefecture: "Versailles",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles plates", "Ardoises", "Zinc"],
    specificProblems: ["Mousse", "Pollution", "Grele"],
    averageRoofAge: 42,
    population: 1440000
  },
  "79": {
    code: "79",
    name: "Deux-Sevres",
    slug: "deux-sevres",
    region: "Nouvelle-Aquitaine",
    prefecture: "Niort",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Ardoises"],
    specificProblems: ["Humidite", "Mousse", "Grele"],
    averageRoofAge: 45,
    population: 375000
  },
  "80": {
    code: "80",
    name: "Somme",
    slug: "somme",
    region: "Hauts-de-France",
    prefecture: "Amiens",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles mecaniques", "Ardoises", "Zinc"],
    specificProblems: ["Humidite", "Sel marin", "Vent"],
    averageRoofAge: 45,
    population: 575000
  },
  "81": {
    code: "81",
    name: "Tarn",
    slug: "tarn",
    region: "Occitanie",
    prefecture: "Albi",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Ardoises"],
    specificProblems: ["Grele", "Vent d'autan", "Secheresse"],
    averageRoofAge: 42,
    population: 390000
  },
  "82": {
    code: "82",
    name: "Tarn-et-Garonne",
    slug: "tarn-et-garonne",
    region: "Occitanie",
    prefecture: "Montauban",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Tuiles mecaniques"],
    specificProblems: ["Grele severe", "Vent d'autan", "Secheresse"],
    averageRoofAge: 42,
    population: 260000
  },
  "83": {
    code: "83",
    name: "Var",
    slug: "var",
    region: "Provence-Alpes-Cote d'Azur",
    prefecture: "Toulon",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Terrasses"],
    specificProblems: ["Incendies", "Sel marin", "Soleil intense"],
    averageRoofAge: 35,
    population: 1070000
  },
  "84": {
    code: "84",
    name: "Vaucluse",
    slug: "vaucluse",
    region: "Provence-Alpes-Cote d'Azur",
    prefecture: "Avignon",
    climate: "mediterraneen",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Terrasses"],
    specificProblems: ["Mistral violent", "Soleil intense", "Secheresse"],
    averageRoofAge: 40,
    population: 560000
  },
  "85": {
    code: "85",
    name: "Vendee",
    slug: "vendee",
    region: "Pays de la Loire",
    prefecture: "La Roche-sur-Yon",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles mecaniques", "Ardoises"],
    specificProblems: ["Tempetes", "Sel marin", "Humidite"],
    averageRoofAge: 38,
    population: 685000
  },
  "86": {
    code: "86",
    name: "Vienne",
    slug: "vienne",
    region: "Nouvelle-Aquitaine",
    prefecture: "Poitiers",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles canal", "Tuiles romanes", "Ardoises"],
    specificProblems: ["Humidite", "Mousse", "Grele"],
    averageRoofAge: 45,
    population: 440000
  },
  "87": {
    code: "87",
    name: "Haute-Vienne",
    slug: "haute-vienne",
    region: "Nouvelle-Aquitaine",
    prefecture: "Limoges",
    climate: "oceanique",
    mainRoofTypes: ["Ardoises", "Tuiles mecaniques", "Tuiles canal"],
    specificProblems: ["Pluies abondantes", "Mousse", "Gel"],
    averageRoofAge: 48,
    population: 375000
  },
  "88": {
    code: "88",
    name: "Vosges",
    slug: "vosges",
    region: "Grand Est",
    prefecture: "Epinal",
    climate: "continental",
    mainRoofTypes: ["Tuiles mecaniques", "Ardoises", "Bac acier"],
    specificProblems: ["Neige lourde", "Gel severe", "Vent"],
    averageRoofAge: 45,
    population: 365000
  },
  "89": {
    code: "89",
    name: "Yonne",
    slug: "yonne",
    region: "Bourgogne-Franche-Comte",
    prefecture: "Auxerre",
    climate: "semi-oceanique",
    mainRoofTypes: ["Tuiles plates", "Tuiles mecaniques", "Ardoises"],
    specificProblems: ["Gel", "Grele", "Mousse"],
    averageRoofAge: 48,
    population: 340000
  },
  "90": {
    code: "90",
    name: "Territoire de Belfort",
    slug: "territoire-de-belfort",
    region: "Bourgogne-Franche-Comte",
    prefecture: "Belfort",
    climate: "continental",
    mainRoofTypes: ["Tuiles mecaniques", "Tuiles plates", "Ardoises"],
    specificProblems: ["Gel severe", "Neige", "Vent"],
    averageRoofAge: 42,
    population: 145000
  },
  "91": {
    code: "91",
    name: "Essonne",
    slug: "essonne",
    region: "Ile-de-France",
    prefecture: "Evry-Courcouronnes",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles mecaniques", "Tuiles plates", "Ardoises"],
    specificProblems: ["Pollution", "Mousse", "Grele"],
    averageRoofAge: 35,
    population: 1310000
  },
  "92": {
    code: "92",
    name: "Hauts-de-Seine",
    slug: "hauts-de-seine",
    region: "Ile-de-France",
    prefecture: "Nanterre",
    climate: "oceanique",
    mainRoofTypes: ["Zinc", "Terrasses", "Tuiles mecaniques"],
    specificProblems: ["Pollution", "Etancheite terrasses", "Pigeons"],
    averageRoofAge: 50,
    population: 1620000
  },
  "93": {
    code: "93",
    name: "Seine-Saint-Denis",
    slug: "seine-saint-denis",
    region: "Ile-de-France",
    prefecture: "Bobigny",
    climate: "oceanique",
    mainRoofTypes: ["Terrasses", "Zinc", "Tuiles mecaniques"],
    specificProblems: ["Pollution", "Etancheite", "Vieillissement"],
    averageRoofAge: 45,
    population: 1650000
  },
  "94": {
    code: "94",
    name: "Val-de-Marne",
    slug: "val-de-marne",
    region: "Ile-de-France",
    prefecture: "Creteil",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles mecaniques", "Terrasses", "Zinc"],
    specificProblems: ["Pollution", "Mousse", "Etancheite"],
    averageRoofAge: 42,
    population: 1400000
  },
  "95": {
    code: "95",
    name: "Val-d'Oise",
    slug: "val-doise",
    region: "Ile-de-France",
    prefecture: "Cergy",
    climate: "oceanique",
    mainRoofTypes: ["Tuiles mecaniques", "Tuiles plates", "Ardoises"],
    specificProblems: ["Mousse", "Pollution", "Grele"],
    averageRoofAge: 38,
    population: 1250000
  }
}

export function getDepartmentBySlug(slug: string): DepartmentData | undefined {
  return Object.values(departmentsData).find(d => d.slug === slug)
}

export function getDepartmentByCode(code: string): DepartmentData | undefined {
  return departmentsData[code]
}

export function getDepartmentsByRegion(region: string): DepartmentData[] {
  return Object.values(departmentsData).filter(d => d.region === region)
}

export function getAllDepartments(): DepartmentData[] {
  return Object.values(departmentsData)
}
